import { Link } from 'react-router-dom'
import { useState } from 'react'
import logoNavbar from '/files/logo-navbar.svg'
import logoMark from '/files/logo-mark.svg'
import NavIcon from '../components/NavIcon'

const features = [
  ['products', 'إدارة المنتجات', 'أضف منتجاتك وصورها وأسعار الشراء والبيع ووحدات القياس في مكان واحد.'],
  ['inventory', 'مخزون دقيق', 'تابع الكمية والحركة والتنبيهات، وعدّل المخزون بسجل واضح لكل عملية.'],
  ['sales', 'فواتير ومبيعات', 'أنشئ الفواتير، أضف العملاء، وسجّل المرتجعات مع تحديث المخزون تلقائياً.'],
  ['analytics', 'يعمل أينما كنت', 'ثبّته كتطبيق على الهاتف أو سطح المكتب، واستمر في العمل حتى عند انقطاع الشبكة.'],
]

function DashboardPreview() {
  return <div className="relative mx-auto w-full max-w-[570px] rounded-[2rem] border border-white/20 bg-white/95 p-3 shadow-2xl shadow-indigo-950/40 backdrop-blur animate-[float_7s_ease-in-out_infinite]" dir="rtl">
    <div className="flex items-center justify-between rounded-2xl bg-slate-950 px-4 py-3 text-white"><img src={logoNavbar} alt="دكان إكس" className="h-7" /><span className="rounded-full bg-white/10 px-2 py-1 text-[10px]">لوحة الإدارة</span></div>
    <div className="grid grid-cols-3 gap-2 py-3"><div className="rounded-xl bg-indigo-50 p-3"><p className="text-[10px] text-slate-500">المنتجات</p><b className="text-lg text-indigo-700">١٢٨</b></div><div className="rounded-xl bg-lime-50 p-3"><p className="text-[10px] text-slate-500">مبيعات اليوم</p><b className="text-lg text-lime-700">٨٬٤٥٠</b></div><div className="rounded-xl bg-amber-50 p-3"><p className="text-[10px] text-slate-500">تنبيهات المخزون</p><b className="text-lg text-amber-600">٣</b></div></div>
    <div className="rounded-2xl border border-slate-100 p-3"><div className="mb-3 flex justify-between"><b className="text-sm text-slate-800">الأصناف الأكثر مبيعاً</b><span className="text-xs text-indigo-600">عرض الكل</span></div>{[['قهوة محمصة','٧٤٪'],['أرز بسمتي','٥٨٪'],['شاي فاخر','٤٢٪']].map(([name, width]) => <div key={name} className="mb-3"><div className="mb-1 flex justify-between text-xs text-slate-600"><span>{name}</span><span>{width}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-l from-lime-400 to-indigo-500" style={{width}} /></div></div>)}</div>
    <div className="absolute -bottom-5 -left-5 rounded-2xl border border-white/70 bg-white px-4 py-3 shadow-lg"><p className="text-[10px] text-slate-500">فاتورة جديدة</p><p className="text-sm font-bold text-slate-900">تم تحديث المخزون ✓</p></div>
  </div>
}


const WINDOWS_DOWNLOAD = 'https://github.com/IbrahimBaki/Dokkanex/releases/latest/download/DokkanX-Setup-1.2.2.exe'

function DesktopAndContact() {
  const [form, setForm] = useState({ name: '', email: '', message: '' })
  const [status, setStatus] = useState('')
  function submit(event) {
    event.preventDefault()
    const recipient = import.meta.env.VITE_SUPPORT_EMAIL || 'ibbaqi@gmail.com'
    if (!recipient) { setStatus('تم حفظ رسالتك محلياً. حدّد VITE_SUPPORT_EMAIL لتفعيل الإرسال إلى بريد الدعم.'); return }
    const subject = encodeURIComponent(`رسالة من ${form.name} عبر موقع دكان إكس`)
    const body = encodeURIComponent(`الاسم: ${form.name}\nالبريد: ${form.email}\n\n${form.message}`)
    window.location.href = `mailto:${recipient}?subject=${subject}&body=${body}`
    setStatus('تم فتح تطبيق البريد لإرسال رسالتك.')
  }
  return <section className="bg-white px-5 py-24"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-2"><article className="overflow-hidden rounded-[2rem] bg-slate-950 p-7 text-white shadow-xl sm:p-10"><span className="inline-flex rounded-xl bg-blue-500/15 px-3 py-1 text-xs font-bold text-blue-200">نسخة سطح المكتب</span><h2 className="mt-5 text-3xl font-black">كل ما تحتاجه، على حاسوبك أيضاً.</h2><p className="mt-4 max-w-md leading-7 text-slate-300">نسخة DokkanX لنظام Windows تمنحك تجربة مكتبية سريعة، مع مزامنة بياناتك عند عودة الاتصال بالإنترنت.</p><ul className="mt-6 space-y-3 text-sm text-slate-200"><li>✓ Windows 10 وWindows 11</li><li>✓ العمل دون اتصال ثم المزامنة لاحقاً</li><li>✓ نفس الحساب ونفس البيانات</li></ul><a href={WINDOWS_DOWNLOAD} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-lime-300 px-5 py-3 font-bold text-slate-950 transition hover:bg-lime-200">تحميل نسخة Windows ↓</a></article><article className="rounded-[2rem] border border-slate-200 bg-[#F8FAFF] p-7 sm:p-10"><p className="text-sm font-bold text-indigo-600">تواصل معنا</p><h2 className="mt-2 text-3xl font-black">كيف يمكننا مساعدتك؟</h2><p className="mt-3 text-sm leading-6 text-slate-600">أرسل استفسارك أو اقتراحك، وسنصل إليك عبر البريد الإلكتروني.</p><form onSubmit={submit} className="mt-6 grid gap-3"><input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} className="input-field" placeholder="الاسم" /><input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} className="input-field" placeholder="البريد الإلكتروني" /><textarea required value={form.message} onChange={e => setForm({ ...form, message: e.target.value })} className="input-field min-h-28 resize-y" placeholder="اكتب رسالتك" /><button className="btn-primary py-3">إرسال الرسالة</button>{status && <p className="text-xs text-slate-500">{status}</p>}</form></article></div></section>
}

export default function LandingPage() {
 return <main dir="rtl" className="overflow-hidden bg-[#F8FAFF] text-slate-900">
  <section className="relative isolate overflow-hidden bg-[#14103A] pb-24 pt-6 text-white sm:pb-32"><div className="absolute -right-32 top-10 h-96 w-96 rounded-full bg-indigo-500/30 blur-3xl animate-pulse" /><div className="absolute -bottom-40 -left-20 h-96 w-96 rounded-full bg-lime-400/15 blur-3xl" />
   <nav className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-5"><img src={logoNavbar} alt="دكان إكس" className="h-10" /><div className="flex items-center gap-3"><Link to="/login" className="hidden text-sm font-semibold text-indigo-100 hover:text-white sm:block">تسجيل الدخول</Link><Link to="/register" className="rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-indigo-800 transition hover:bg-lime-100">ابدأ مجاناً</Link></div></nav>
   <div className="relative z-10 mx-auto grid max-w-7xl items-center gap-14 px-5 pt-20 lg:grid-cols-2"><div><span className="inline-flex items-center gap-2 rounded-full border border-lime-300/30 bg-lime-300/10 px-3 py-1.5 text-xs font-bold text-lime-200">● مصمم لعمل المتاجر اليومي</span><h1 className="mt-6 text-4xl font-black leading-[1.18] sm:text-6xl">أدر متجرك بثقة،<br /><span className="bg-gradient-to-l from-lime-300 to-indigo-200 bg-clip-text text-transparent">ودَع التفاصيل تعمل لصالحك.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-indigo-100">دكان إكس هو مساحة عمل متكاملة لإدارة المنتجات والمخزون والمبيعات والفواتير من هاتفك أو حاسوبك.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/register" className="rounded-xl bg-lime-300 px-6 py-3.5 font-bold text-slate-950 shadow-lg shadow-lime-300/20 transition hover:-translate-y-0.5">أنشئ حسابك مجاناً ←</Link><button type="button" onClick={() => document.getElementById('features')?.scrollIntoView({ behavior: 'smooth' })} className="rounded-xl border border-white/20 px-6 py-3.5 font-bold text-white transition hover:bg-white/10">اكتشف المزايا</button></div><div className="mt-10 flex gap-6 text-sm text-indigo-200"><span>✓ دون رسوم خفية</span><span>✓ مزامنة تلقائية</span><span>✓ عربي بالكامل</span></div></div><DashboardPreview /></div>
  </section>
  <section id="features" className="mx-auto max-w-7xl px-5 py-24"><div className="max-w-2xl"><p className="text-sm font-bold text-indigo-600">أدواتك اليومية، في مكان واحد</p><h2 className="mt-3 text-3xl font-black leading-tight sm:text-4xl">كل ما يحتاجه المتجر ليعمل بصورة أذكى.</h2><p className="mt-4 leading-7 text-slate-600">واجهة واضحة، وعمليات مترابطة: كل عملية بيع أو مرتجع تنعكس مباشرة على ما تراه في مخزونك وتقاريرك.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(([icon, title, desc], i) => <article key={title} className="group rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-indigo-200 hover:shadow-xl hover:shadow-indigo-100"><span className={`flex h-12 w-12 items-center justify-center rounded-2xl ${i === 3 ? 'bg-lime-100 text-lime-700' : 'bg-indigo-50 text-indigo-700'}`}><NavIcon name={icon} className="h-6 w-6" /></span><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{desc}</p></article>)}</div></section>
  <section className="bg-slate-950 px-5 py-24 text-white"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><div><p className="text-sm font-bold text-lime-300">مسار عمل متصل</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">من المنتج إلى الفاتورة، دون تكرار أو فوضى.</h2><p className="mt-5 max-w-lg leading-8 text-slate-300">أضف منتجاً، حدّد كميته، ثم استخدمه في فاتورة بيع. يحسب دكان إكس الإجمالي ويخصم الكمية، ويحتفظ بسجل للمرتجعات.</p></div><div className="grid gap-3">{[['١','أضف بيانات المنتج وصورته وسعره.'],['٢','تابع الكميات وتعديلات المخزون.'],['٣','أنشئ فاتورة باسم متجرك وشاركها أو اطبعها.']].map(([n,t]) => <div key={n} className="flex items-center gap-4 rounded-2xl border border-white/10 bg-white/5 p-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-lime-300 font-black text-slate-950">{n}</span><p className="font-semibold text-slate-100">{t}</p></div>)}</div></div></section>
  <DesktopAndContact />
  <section className="px-5 py-24"><div className="mx-auto max-w-5xl rounded-[2rem] bg-gradient-to-l from-indigo-700 to-violet-700 px-7 py-14 text-center text-white shadow-2xl shadow-indigo-200 sm:px-16"><img src={logoMark} alt="دكان إكس" className="mx-auto h-16 w-16" /><h2 className="mt-6 text-3xl font-black sm:text-4xl">ابدأ بإدارة متجر أكثر وضوحاً.</h2><p className="mx-auto mt-4 max-w-2xl text-indigo-100">استخدمه من المتصفح، أو ثبّته كتطبيق PWA على هاتفك للوصول الأسرع.</p><Link to="/register" className="mt-8 inline-block rounded-xl bg-lime-300 px-7 py-3.5 font-bold text-slate-950 transition hover:bg-lime-200">ابدأ الآن مجاناً</Link></div></section>
  <footer className="border-t border-slate-200 px-5 py-8"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-3 text-sm text-slate-500 sm:flex-row"><img src={logoNavbar} alt="دكان إكس" className="h-8" /><span>© {new Date().getFullYear()} دكان إكس — إدارة أبسط لدكانك.</span></div></footer>
 </main>
}
