import { afterEach, describe, expect, it } from 'vitest';
import { createDatabase } from '../../src/lib/db';
import { archiveProduct, createCategory, createProduct, createProductWithOpeningStock, deleteCategory, updateCategory, updateProductMetadata } from '../../src/lib/catalogV2';
import { queueImageReplacement } from '../../src/lib/v2Images';
import { createV2SyncRunner } from '../../src/lib/v2Sync';
import { selectReadyOutbox } from '../../src/lib/v2Sync';
import { transitionOutboxOperation } from '../../src/lib/outbox';

const A='user-a', B='user-b', databases=[];
async function fresh(){const database=createDatabase(`catalog-${crypto.randomUUID()}`);databases.push(database);await database.open();return database;}
afterEach(async()=>Promise.all(databases.splice(0).map(async d=>{d.close();await d.delete();})));
describe('V2 catalog write foundation',()=>{
  it('creates a local product and stable V2 create intent atomically without V1 queue work',async()=>{const db=await fresh();const {product,operation}=await createProduct({userId:A,id:'p',name:'P',wholesale_price:2,selling_price:5,unit:'piece'},db);expect(product.user_id).toBe(A);expect(operation).toMatchObject({operation_id:'p',entity_type:'product',action:'create',payload:expect.objectContaining({wholesale_price:2,selling_price:5})});expect(await db.sync_queue.count()).toBe(0);});
  it('keeps blank opening stock unset, but atomically creates exact zero/decimal openings behind product create',async()=>{const db=await fresh();await createProduct({userId:A,id:'blank',name:'Blank',wholesale_price:1,selling_price:2},db);expect(await db.inventory_balances.get('blank')).toBeUndefined();const zero=await createProductWithOpeningStock({userId:A,id:'zero',name:'Zero',wholesale_price:1,selling_price:2,openingQuantity:'0'},db);expect(zero.opening.balance.current_quantity).toBe('0.000000');expect(zero.opening.operation.depends_on).toBe(zero.operation.operation_id);const decimal=await createProductWithOpeningStock({userId:A,id:'decimal',name:'Decimal',wholesale_price:1,selling_price:2,openingQuantity:'2.125'},db);expect(decimal.opening.balance.current_quantity).toBe('2.125000');expect((await db.inventory_movements.get(decimal.opening.movement.id)).qty_change).toBe('2.125000');expect(await db.sync_queue.count()).toBe(0);});
  it('makes same-user category create precede product create and product create precede opening',async()=>{const db=await fresh();const {category,operation:categoryCreate}=await createCategory({userId:A,id:'c',name:'C'},db);const created=await createProductWithOpeningStock({userId:A,id:'p',name:'P',wholesale_price:1,selling_price:2,category_id:category.id,openingQuantity:'1'},db);expect(created.operation.depends_on).toBe(categoryCreate.operation_id);expect(created.opening.operation.depends_on).toBe(created.operation.operation_id);expect((await selectReadyOutbox(A,db)).map(x=>x.operation_id)).toEqual([categoryCreate.operation_id]);});
  it('rolls back product and opening business state when local opening persistence fails',async()=>{const db=await fresh();const original=db.inventory_balances.add;db.inventory_balances.add=async()=>{throw new Error('forced balance failure');};await expect(createProductWithOpeningStock({userId:A,id:'rollback',name:'Rollback',wholesale_price:1,selling_price:2,openingQuantity:'1'},db)).rejects.toThrow('forced balance failure');db.inventory_balances.add=original;expect(await db.products.get('rollback')).toBeUndefined();expect(await db.outbox_operations.get('rollback')).toBeUndefined();expect(await db.inventory_movements.where('product_id').equals('rollback').count()).toBe(0);});
  it('blocks metadata and archive behind an unresolved same-user product create',async()=>{const db=await fresh();const {operation:create}=await createProduct({userId:A,id:'p',name:'P',wholesale_price:1,selling_price:2},db);const metadata=await updateProductMetadata({userId:A,productId:'p',patch:{name:'P2'},operationId:'m'},db);const archive=await archiveProduct({userId:A,productId:'p',operationId:'a'},db);expect([metadata.depends_on,archive.depends_on]).toEqual([create.operation_id,create.operation_id]);expect((await selectReadyOutbox(A,db)).map(x=>x.operation_id)).toEqual([create.operation_id]);await transitionOutboxOperation(create.operation_id,'syncing',{},db);await transitionOutboxOperation(create.operation_id,'retryable_failed',{},db);expect((await selectReadyOutbox(A,db)).map(x=>x.operation_id)).toEqual([create.operation_id]);});
  it('captures metadata version and changes purchase and selling prices without inventory mutation',async()=>{const db=await fresh();await db.products.put({id:'p',user_id:A,metadata_version:7,wholesale_price:2,selling_price:5});await db.inventory_balances.put({product_id:'p',user_id:A,current_quantity:'9'});const op=await updateProductMetadata({userId:A,productId:'p',patch:{wholesale_price:3,selling_price:6,cost_price:99},operationId:'m'},db);expect(op.payload).toEqual({expected_metadata_version:7,patch:{wholesale_price:3,selling_price:6}});expect(await db.products.get('p')).toMatchObject({wholesale_price:3,selling_price:6});expect(await db.inventory_balances.get('p')).toMatchObject({current_quantity:'9'});});
  it('queues archive without hard deleting and category commands use V2 only',async()=>{const db=await fresh();await db.products.put({id:'p',user_id:A});await archiveProduct({userId:A,productId:'p',operationId:'archive'},db);expect(await db.products.get('p')).toBeTruthy();const {category}=await createCategory({userId:A,id:'c',name:'C'},db);await updateCategory({userId:A,categoryId:category.id,patch:{name:'D'},operationId:'cu'},db);await deleteCategory({userId:A,categoryId:category.id,operationId:'cd'},db);expect((await db.outbox_operations.where('user_id').equals(A).toArray()).map(x=>x.action)).toEqual(expect.arrayContaining(['archive','create','update','delete']));expect(await db.sync_queue.count()).toBe(0);});
  it('does not permit category identity or ownership mutation',async()=>{const db=await fresh();await createCategory({userId:A,id:'c',name:'C'},db);await updateCategory({userId:A,categoryId:'c',patch:{id:'other',user_id:B,created_at:'never',name:'D'},operationId:'safe'},db);expect(await db.categories.get('c')).toMatchObject({id:'c',user_id:A,name:'D'});expect(await db.categories.get('other')).toBeUndefined();expect((await db.outbox_operations.get('safe')).payload).toMatchObject({id:'c',user_id:A,name:'D'});});
  it('enforces catalog ownership and composes product create to image upload to metadata',async()=>{const db=await fresh();await db.products.put({id:'b',user_id:B});await expect(updateProductMetadata({userId:A,productId:'b',patch:{name:'no'}} ,db)).rejects.toThrow('does not belong');const {operation}=await createProduct({userId:A,id:'p',name:'P',wholesale_price:1,selling_price:2},db);const image=await queueImageReplacement({userId:A,productId:'p',operationId:'img',image:'x',expectedMetadataVersion:0,dependsOn:operation.operation_id},db);expect(image.operation.depends_on).toBe('p');});
  it('reconciles a duplicate create only to the same owner canonical product',async()=>{const db=await fresh();await createProduct({userId:A,id:'p',name:'P',wholesale_price:1,selling_price:2},db);const canonical={id:'p',user_id:A,name:'P',image_url:null,wholesale_price:1,selling_price:2,category_id:null,unit:'piece',low_stock_threshold:null};const chain={eq:()=>chain,neq:()=>chain,gt:()=>chain,order:()=>chain,single:async()=>({data:canonical,error:null}),then:r=>r({data:[],error:null})};const client={auth:{getSession:async()=>({data:{session:{user:{id:A}}}})},from:()=>({insert:()=>({select:()=>({single:async()=>({data:null,error:{code:'23505'}})})}),select:()=>chain})};await createV2SyncRunner({client,database:db}).sync(A);expect(await db.outbox_operations.get('p')).toMatchObject({status:'succeeded',server_receipt:{recovered_duplicate:true}});});
});
